name: CI

on: [push]

jobs:
  cpp_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run C++ tests
      run: make all

  python_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: cclauss/GitHub-Action-for-pytest@master
    - name: Run Python tests
      run: PYTHONPATH=framework/ pytest framework/spec
