name: CI

on: [push]

jobs:
  cpp-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install quom
    - name: Build and run C++ tests
      run: make all
