name: CI

on: [push]

jobs:
  ubuntu-cpp-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install quom && sudo apt-get install -y ninja-build
    - name: Run all tests
      run: make test

  macos-cpp-tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install quom
    - name: Run all tests
      run: mkdir build && cd build && cmake .. && make
